### ISSUE TITLE
Task rev: srcset

### ISSUE THREAD

**Issue by Hessel88** [nexumAG/generator-atomic#20]
grunt-rev does not update paths in html 'srcset'. Please look into the issue at:

https://github.com/yeoman/grunt-usemin/issues/428

Do we have a fix for this? Otherwise we should list it as a known issue.

**Comment by michaseel** [comment]
This Issue is not related to this project.
Please report / fix it in the grunt-usemin project (yeoman/grunt-usemin#428)
